### ISSUE TITLE
wallpaper good look, ask to share

### ISSUE THREAD

**Issue by zwsn** [KrautGTI/glass-theme-doyle#3]
Can you share the wallpaper in this picture？
![image](https://github.com/KrautGTI/glass-theme-doyle/assets/42889307/dd365244-d130-4b55-8d95-32a6e10e4e21)

**Comment by KrautGTI** [comment]
haha thank you! Here you go! sorry for the delay
![GradientBG](https://github.com/KrautGTI/glass-theme-doyle/assets/94489438/549c00c8-64c8-4546-acb5-1d665b1c5252)

**Comment by KrautGTI** [comment]
I have two vertical monitors and a 49 inch ultrawide monitor and it looks fine for all 3 monitors @zwsn
